we have to create an array of random integers between 1 to 50 with shape (5,4)


In [1]:
import numpy as np
import pandas as pd
arr=np.random.randint(1,51,size=(5,4))
print(arr)

[[41 15 26 24]
 [23 32 35 16]
 [35 47 15 28]
 [21 40 49 10]
 [50 10 11  4]]


now we have to extract the elements along anti diagonal

In [2]:
 for i in range(min(arr.shape)):
     print(arr[i,-1-i])


24
35
47
21


now we have to compute and print the max value in each row


In [3]:
max_val=np.max(arr,axis=1)
print('maximum value of each row is :',max_val)
    
    

maximum value of each row is : [41 35 47 49 50]


we have to create a array less than or equal to the mean of the original array


In [4]:
print('Mean :',np.mean(arr))

Mean : 26.6


In [5]:
filteredarr=arr[arr<=27.55]
print(filteredarr)

[15 26 24 23 16 15 21 10 10 11  4]


we have to write a boundary traversal function

In [6]:
#creating a function that travels on the boundary of a given matrix
def numpy_boundary_traversal(matrix):
    top=matrix[0,:]
    right=matrix[1:-1,-1]
    bottom=matrix[-1,::-1]
    left=matrix[-2:0:-1,0]
    return np.concatenate([top.flatten(),right.flatten(),bottom.flatten(),left.flatten()])
    
    
        
    
    



In [7]:
matrix=[[46 ,20, 36, 38],
 [27 ,35 ,34, 28],
 [ 6 ,36, 17 ,21],
 [40, 44, 43 , 7],
 [39 ,20,  3, 11]]
matrix=np.array(matrix)

In [8]:
numpy_boundary_traversal(matrix)

array([46, 20, 36, 38, 28, 21,  7, 11,  3, 20, 39, 40,  6, 27])

# question 2

Create a 1-dimensional NumPy array of 20 random floats between 0 and 10. Perform the following tasks:
- Print the array and round all elements to two decimal places.
- Calculate and print the minimum, maximum, and median of the array.
- Replace all elements less than 5 with their squares.
- Write a Python function numpy_alternate_sort(array) that takes a 1D NumPy array and returns a new array with elements sorted in an alternating pattern (smallest, largest, second smallest, second largest, etc.)



In [9]:
import numpy as np
import pandas as pd

In [10]:
arr=np.random.uniform(0,10,20)

In [11]:
print('array is :',arr)

array is : [4.07669835 6.92532939 7.52387017 6.89582167 9.6256205  4.39683374
 3.8725139  4.77479981 8.88419711 3.45562817 8.32402538 9.68099594
 3.96371468 1.26423215 9.71182469 2.09480284 2.89200616 4.58432759
 1.22540819 9.25547691]


In [12]:
# round the array to two decimal places
round_arr=np.round(arr,2)
print ('Rounded array is :',round_arr)

Rounded array is : [4.08 6.93 7.52 6.9  9.63 4.4  3.87 4.77 8.88 3.46 8.32 9.68 3.96 1.26
 9.71 2.09 2.89 4.58 1.23 9.26]


In [13]:
minimum=np.min(arr)
maximum=np.max(arr)
median=np.median(arr)

In [14]:
print('Minimum is :',minimum)
print('Maximum is :',maximum)
print('Median is :',median)

Minimum is : 1.2254081863466249
Maximum is : 9.711824686755852
Median is : 4.679563698914157


In [15]:
#replace the numbers which are less than 5 with their squares
arrrep = arr.copy() 
arrrep[arr<5]=arr[arr<5]**2
print('Replaced array is :',arrrep)

Replaced array is : [16.6194694   6.92532939  7.52387017  6.89582167  9.6256205  19.33214693
 14.9963639  22.79871321  8.88419711 11.94136604  8.32402538  9.68099594
 15.71103408  1.59828292  9.71182469  4.38819895  8.36369961 21.01605945
  1.50162522  9.25547691]


In [16]:
# create a function to sort alternatively
def numpy_alternate_sort(array):
    sorted_arr=np.sort(array)
    result=np.zeros_like(array)
    n=len(array)
    for i in range(n):
        if i%2==0:
            result[i]=sorted_arr[i//2]
        else:
            result[i]=sorted_arr[n-(i//2)-1]
    return result

In [17]:
array=[4.86, 4.42 ,9.21 ,8.11, 4.25 ,6.8,  3.04 ,5.48, 8.68 ,5.94, 7.16 ,8.19 ,8.85, 9.45,
 3.5 , 2.65, 6.36 ,4.77, 6.33 ,4.42]
numpy_alternate_sort(array)

array([2.65, 9.45, 3.04, 9.21, 3.5 , 8.85, 4.25, 8.68, 4.42, 8.19, 4.42,
       8.11, 4.77, 7.16, 4.86, 6.8 , 5.48, 6.36, 5.94, 6.33])

# question 3


Create a Pandas DataFrame with 10 rows representing student records, with columns Name, Subject, Score (random integers between 50 and 100), and Grade (initially empty). Perform the following tasks:
- Assign grades based on scores: A (90–100), B (80–89), C (70–79), D (60–69), F (below 60).
- Print the DataFrame sorted by Score in descending order.
- Calculate and print the average score for each subject.
- Write a Python function pandas_filter_pass(dataframe) that takes a DataFrame and returns a new DataFrame containing only the records with grades A or B.


In [18]:
import numpy as np 
import pandas as pd

In [19]:
# generate the required dataframe
names = ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia']
subjects = ['Math', 'Science', 'English', 'History', 'Physics', 'Chemistry', 'Biology', 'Art', 'Music', 'Geography']
df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': np.random.randint(50, 101, size=10),  # Random integers between 50 and 100
    'Grade': ''  # Initially empty
})

In [20]:
# create a function assign grade 
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)
print(df)


      Name    Subject  Score Grade
0    Alice       Math     63     D
1      Bob    Science     61     D
2  Charlie    English     54     F
3    David    History     68     D
4     Emma    Physics     73     C
5    Frank  Chemistry     96     A
6    Grace    Biology     95     A
7   Hannah        Art     81     B
8      Ian      Music     90     A
9    Julia  Geography     89     B


In [21]:
df_sorted=df.sort_values('Score')

In [22]:
print(df_sorted)

      Name    Subject  Score Grade
2  Charlie    English     54     F
1      Bob    Science     61     D
0    Alice       Math     63     D
3    David    History     68     D
4     Emma    Physics     73     C
7   Hannah        Art     81     B
9    Julia  Geography     89     B
8      Ian      Music     90     A
6    Grace    Biology     95     A
5    Frank  Chemistry     96     A


In [23]:
#grouping the scores of same subject
average_by_subject = df.groupby('Subject')['Score'].mean()

In [24]:
print(average_by_subject)

Subject
Art          81.0
Biology      95.0
Chemistry    96.0
English      54.0
Geography    89.0
History      68.0
Math         63.0
Music        90.0
Physics      73.0
Science      61.0
Name: Score, dtype: float64


In [25]:
#create a filter pass function that has dataframe only with grade A or B
def pandas_filter_pass(dataframe) :
    df_filt=dataframe[dataframe['Grade'].isin(['A', 'B'])]
    return df_filt

In [26]:
pandas_filter_pass(df)

Name    Subject  Score Grade
5   Frank  Chemistry     96     A
6   Grace    Biology     95     A
7  Hannah        Art     81     B
8     Ian      Music     90     A
9   Julia  Geography     89     B

# question 4

Create a synthetic dataset which is a list of 100 short movie reviews (50 positive, 50 negative) stored in a Pandas DataFrame with columns Review (text) and Sentiment (positive/negative). Perform the following tasks:

- Tokenize the reviews using CountVectorizer with a maximum of 500 features, removing stop words.
- Split the dataset into training (80%) and testing (20%) sets using train_test_split.
- Train a Multinomial Naive Bayes classifier on the tokenized training data and print the accuracy on the test set.
- Write a Python function predict_review_sentiment(model, vectorizer, review) that takes a trained model, the fitted CountVectorizer, and a single review (string), and returns the predicted sentiment.


In [27]:
import pandas as pd
import numpy as np
import random
np.random.seed(42)
random.seed(42)

# Create lists of positive and negative phrases to build reviews
positive_phrases = [
    "loved the movie", "brilliant performance", "outstanding cinematography", 
    "excellent plot", "well directed", "captivating story", "amazing visual effects",
    "great character development", "powerful soundtrack", "emotional journey",
    "masterpiece", "worth watching", "incredible acting", "beautifully shot",
    "engaging from start to finish"
]

negative_phrases = [
    "waste of time", "terrible acting", "poor direction", "boring plot",
    "predictable storyline", "disappointing ending", "awful dialogue",
    "poorly executed", "weak characters", "bad pacing", "confusing narrative",
    "overrated", "fell asleep", "not worth the money", "forgettable"
]

# Additional adjectives to add variety
positive_adj = ["amazing", "fantastic", "excellent", "superb", "wonderful", "brilliant", "delightful"]
negative_adj = ["terrible", "awful", "horrible", "disappointing", "dreadful", "mediocre", "poor"]

# Generate 50 positive reviews
positive_reviews = []
for _ in range(50):
    base = random.choice(positive_phrases)
    adj = random.choice(positive_adj)
    
    # Create different review structures for variety
    structure = random.randint(1, 4)
    if structure == 1:
        review = f"I {base}. It was a {adj} film."
    elif structure == 2:
        review = f"This movie had {base}. {adj.capitalize()} experience overall."
    elif structure == 3:
        review = f"A {adj} film with {base}."
    else:
        review = f"{base.capitalize()}! I would definitely recommend this {adj} movie."
    
    positive_reviews.append(review)

# Generate 50 negative reviews
negative_reviews = []
for _ in range(50):
    base = random.choice(negative_phrases)
    adj = random.choice(negative_adj)
    
    # Create different review structures for variety
    structure = random.randint(1, 4)
    if structure == 1:
        review = f"I found it {base}. Such a {adj} movie."
    elif structure == 2:
        review = f"This film was {base}. {adj.capitalize()} experience overall."
    elif structure == 3:
        review = f"A {adj} movie with {base}."
    else:
        review = f"{base.capitalize()}. I would not recommend this {adj} film."
    
    negative_reviews.append(review)

# Create DataFrame
reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

# Shuffle the data while keeping reviews and sentiments aligned
combined = list(zip(reviews, sentiments))
random.shuffle(combined)
reviews, sentiments = zip(*combined)

# Create the final DataFrame
movie_reviews_df = pd.DataFrame({
    'Review': reviews,
    'Sentiment': sentiments
})

# Display the first few rows
print(f"Dataset shape: {movie_reviews_df.shape}")
print("\nSample reviews:")
movie_reviews_df.head(10)

Dataset shape: (100, 2)

Sample reviews:


Review Sentiment
0  I found it terrible acting. Such a mediocre mo...  negative
1  This movie had well directed. Fantastic experi...  positive
2             A terrible movie with weak characters.  negative
3       I beautifully shot. It was a fantastic film.  positive
4        I excellent plot. It was a delightful film.  positive
5         I worth watching. It was a brilliant film.  positive
6       I powerful soundtrack. It was a superb film.  positive
7  This film was fell asleep. Disappointing exper...  negative
8      I incredible acting. It was a excellent film.  positive
9  Terrible acting. I would not recommend this ho...  negative

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Assuming movie_reviews_df is already created from the previous code

# Step 1: Tokenize the reviews using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(movie_reviews_df['Review'])
y = movie_reviews_df['Sentiment']

# Step 2: Split the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Train a Multinomial Naive Bayes classifier
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = nb_classifier.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy:.4f}")

# Print detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 4: Create the prediction function
def predict_review_sentiment(model, vectorizer, review):
    """
    Predicts the sentiment of a single movie review.
    
    Parameters:
    -----------
    model : trained classifier model
        The trained machine learning model
    vectorizer : CountVectorizer
        The fitted CountVectorizer used to transform text
    review : str
        The movie review text to classify
        
    Returns:
    --------
    str
        The predicted sentiment ('positive' or 'negative')
    """
    # Transform the review text using the same vectorizer
    review_vectorized = vectorizer.transform([review])
    
    # Predict the sentiment
    prediction = model.predict(review_vectorized)[0]
    
    return prediction

# Demonstrate the function with a few examples
example_reviews = [
    "This movie was fantastic! I loved every minute of it.",
    "What a waste of time. The acting was terrible and the plot made no sense.",
    "I'm not sure how I feel about this film. It had good and bad moments."
]

print("\nPrediction Examples:")
for review in example_reviews:
    sentiment = predict_review_sentiment(nb_classifier, vectorizer, review)
    print(f"Review: '{review}'")
    print(f"Predicted sentiment: {sentiment}\n")

# Show the most informative features (words) for each class
def display_most_informative_features(vectorizer, classifier, n=10):
    feature_names = vectorizer.get_feature_names_out()
    class_labels = classifier.classes_
    
    # For each class, find the most important features
    for i, label in enumerate(class_labels):
        top_indices = np.argsort(classifier.feature_log_prob_[i])[-n:]
        top_features = [feature_names[j] for j in top_indices]
        print(f"\nTop {n} features for class '{label}':")
        print(", ".join(top_features))

print("\nMost Informative Features:")
display_most_informative_features(vectorizer, nb_classifier)

Model accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

    negative       1.00      1.00      1.00        12
    positive       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Prediction Examples:
Review: 'This movie was fantastic! I loved every minute of it.'
Predicted sentiment: positive

Review: 'What a waste of time. The acting was terrible and the plot made no sense.'
Predicted sentiment: negative

Review: 'I'm not sure how I feel about this film. It had good and bad moments.'
Predicted sentiment: negative


Most Informative Features:

Top 10 features for class 'negative':
terrible, characters, mediocre, experience, overall, awful, poor, recommend, film, movie

Top 10 features for class 'positive':
superb, acting, definitely, recommend, overall, experience, brilliant, excellent, movie,

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Assuming movie_reviews_df is already created from the previous code

# Step 1: Tokenize the reviews using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(movie_reviews_df['Review'])
y = movie_reviews_df['Sentiment']


Step 2: Split the dataset into training (80%) and testing (20%) sets

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Step 3: Train a Multinomial Naive Bayes classifier

In [31]:
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = nb_classifier.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy:.4f}")

# Print detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Model accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

    negative       1.00      1.00      1.00        12
    positive       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Step 4: Create the prediction function

In [32]:
def predict_review_sentiment(model, vectorizer, review):
    """
    Predicts the sentiment of a single movie review.
    
    Parameters:
    -----------
    model : trained classifier model
        The trained machine learning model
    vectorizer : CountVectorizer
        The fitted CountVectorizer used to transform text
    review : str
        The movie review text to classify
        
    Returns:
    --------
    str
        The predicted sentiment ('positive' or 'negative')
    """
    # Transform the review text using the same vectorizer
    review_vectorized = vectorizer.transform([review])
    
    # Predict the sentiment
    prediction = model.predict(review_vectorized)[0]
    
    return prediction

# Demonstrate the function with a few examples
example_reviews = [
    "This movie was fantastic! I loved every minute of it.",
    "What a waste of time. The acting was terrible and the plot made no sense.",
    "I'm not sure how I feel about this film. It had good and bad moments."
    ]

print("\nPrediction Examples:")
for review in example_reviews:
    sentiment = predict_review_sentiment(nb_classifier, vectorizer, review)
    print(f"Review: '{review}'")
    print(f"Predicted sentiment: {sentiment}\n")

# Show the most informative features (words) for each class
def display_most_informative_features(vectorizer, classifier, n=10):
    feature_names = vectorizer.get_feature_names_out()
    class_labels = classifier.classes_
    
    # For each class, find the most important features
    for i, label in enumerate(class_labels):
        top_indices = np.argsort(classifier.feature_log_prob_[i])[-n:]
        top_features = [feature_names[j] for j in top_indices]
        print(f"\nTop {n} features for class '{label}':")
        print(", ".join(top_features))

print("\nMost Informative Features:")
display_most_informative_features(vectorizer, nb_classifier)


Prediction Examples:
Review: 'This movie was fantastic! I loved every minute of it.'
Predicted sentiment: positive

Review: 'What a waste of time. The acting was terrible and the plot made no sense.'
Predicted sentiment: negative

Review: 'I'm not sure how I feel about this film. It had good and bad moments.'
Predicted sentiment: negative


Most Informative Features:

Top 10 features for class 'negative':
terrible, characters, mediocre, experience, overall, awful, poor, recommend, film, movie

Top 10 features for class 'positive':
superb, acting, definitely, recommend, overall, experience, brilliant, excellent, movie, film


Question 5

Create a synthetic dataset of 100 short text samples (e.g., product feedback) with binary labels (good/bad) and apply an NLP pipeline using scikit-learn. Perform the following tasks:

Preprocess the text using TfidfVectorizer with a maximum of 300 features, applying lowercasing and stop word removal.

Split the dataset into training (75%) and testing (25%) sets.

Train a Logistic Regression model on the vectorized training data and print the precision, recall, and F1-score for the test set.

Write a Python function text_preprocess_vectorize(texts, vectorizer) that takes a list of text samples and a fitted TfidfVectorizer, and returns the vectorized feature matrix



In [33]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import random

# Set random seed for reproducibility
np.random.seed(42)
random.seed(42)

# Create synthetic dataset of 100 short text samples with binary labels
positive_phrases = [
    "excellent product", "works great", "highly recommend", "very satisfied",
    "good quality", "amazing service", "fast delivery", "perfect fit",
    "easy to use", "worth the money", "exceeded expectations", "very durable",
    "fantastic customer support", "best purchase ever", "love it"
]

negative_phrases = [
    "poor quality", "doesn't work", "waste of money", "very disappointed",
    "broke easily", "terrible service", "slow delivery", "doesn't fit",
    "difficult to use", "overpriced", "below expectations", "not durable",
    "no customer support", "worst purchase ever", "hate it"
]

# Generate synthetic reviews
texts = []
labels = []

for _ in range(50):  # 50 positive reviews
    base = random.choice(positive_phrases)
    extra_words = random.randint(0, 5)
    extra = " ".join(random.choice(positive_phrases).split()[:extra_words])
    texts.append(f"{base} {extra}".strip())
    labels.append(1)  # 1 for positive

for _ in range(50):  # 50 negative reviews
    base = random.choice(negative_phrases)
    extra_words = random.randint(0, 5)
    extra = " ".join(random.choice(negative_phrases).split()[:extra_words])
    texts.append(f"{base} {extra}".strip())
    labels.append(0)  # 0 for negative

# Create a DataFrame for better visualization
df = pd.DataFrame({'text': texts, 'label': labels})

In [34]:
df

text  label
0                  exceeded expectations      1
1            very durable very satisfied      1
2                    very satisfied very      1
3               works great very durable      1
4                    love it works great      1
..                                   ...    ...
95       doesn't work below expectations      0
96                  poor quality doesn't      0
97                               hate it      0
98                      terrible service      0
99  very disappointed below expectations      0

[100 rows x 2 columns]

In [35]:
# Shuffle the dataset
df = df.sample(frac=1).reset_index(drop=True)

In [36]:
# Define the text preprocessing and vectorization function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

In [37]:
vectorizer = TfidfVectorizer(
    max_features=300,  # Maximum 300 features
    stop_words='english',  # Remove English stop words
    lowercase=True  # Convert text to lowercase
)

In [38]:
# Fit the vectorizer on the entire dataset
X = vectorizer.fit_transform(df['text'])
y = df['label']

In [39]:
# Split the dataset into training (75%) and testing (25%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [40]:
# Train a Logistic Regression model
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

In [41]:
# Print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Negative', 'Positive']))


Classification Report:
              precision    recall  f1-score   support

    Negative       0.89      1.00      0.94         8
    Positive       1.00      0.94      0.97        17

    accuracy                           0.96        25
   macro avg       0.94      0.97      0.96        25
weighted avg       0.96      0.96      0.96        25



In [42]:
# Example of using the text_preprocess_vectorize function
new_texts = ["This product is amazing", "Terrible experience, don't buy"]
new_features = text_preprocess_vectorize(new_texts, vectorizer)
new_predictions = model.predict(new_features)
print("\nPredictions for new texts:")
for text, pred in zip(new_texts, new_predictions):
    sentiment = "Positive" if pred == 1 else "Negative"
    print(f"Text: '{text}' - Predicted: {sentiment}")


Predictions for new texts:
Text: 'This product is amazing' - Predicted: Positive
Text: 'Terrible experience, don't buy' - Predicted: Negative
